import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {readIssues} from '../scripts/lib/issue-data.mjs';
import {selectEvents} from '../scripts/lib/issue-policy.mjs';
const topic=id=>({id,event:{productKey:id,kind:'release',version:'1',key:'initial-release',occurredAt:'2026-10-06',deltaZh:'有来源的更新',deltaEn:'Sourced update'},eventSourceUrl:`https://example.com/${id}`,sources:[{url:`https://example.com/${id}`,publishedAt:'2026-10-06',verifiedAt:'2026-10-06T16:00:00Z',isPrimary:true}]});
test('Superseded published and shadowed legacy stories remain in cross-day coverage without returning to the visible edition',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'daily-coverage-'));try{await fs.mkdir(path.join(root,'data/editions'),{recursive:true});await fs.mkdir(path.join(root,'data/coverage'));const legacy=JSON.stringify([{date:'2026-10-06',topics:[topic('legacy-hidden')]}]);const edition=JSON.stringify({date:'2026-10-06',topics:[topic('current')]});await fs.writeFile(path.join(root,'data/issues.json'),legacy);await fs.writeFile(path.join(root,'data/editions/2026-10-06.json'),edition);await fs.writeFile(path.join(root,'data/coverage/2026-10-06.json'),JSON.stringify({date:'2026-10-06',publicationCommit:'a'.repeat(40),topics:[topic('published-hidden')]}));const archive=await readIssues(root);assert.deepEqual(archive[0].topics.map(t=>t.id),['current']);assert.deepEqual(new Set(archive[0].coveredTopics.map(t=>t.id)),new Set(['legacy-hidden','published-hidden']));const result=selectEvents([topic('legacy-hidden'),topic('published-hidden')],archive,{date:'2026-10-07',cutoff:'2026-10-07T16:00:00Z',lookbackDays:3});assert.equal(result.topics.length,0);assert.equal(result.excluded.length,2);assert.ok(result.excluded.every(x=>x.reason==='already-covered'));assert.equal(await fs.readFile(path.join(root,'data/issues.json'),'utf8'),legacy);assert.equal(await fs.readFile(path.join(root,'data/editions/2026-10-06.json'),'utf8'),edition);}finally{await fs.rm(root,{recursive:true,force:true});}});
