import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
const script=resolve('scripts/export-pdfs-reportlab.py');
const topic=(id)=>({id,zhHeadline:'有图有文的产品'+id,enHeadline:'An illustrated product '+id,evidenceLabel:'confirmed product',event:{productKey:id,kind:'release',occurredAt:'2026-10-06'},brief:{zh:{what:'这是一台运行本地模型的设备',change:'今天开放有明确日期的新功能',use:'通过真实交互流程完成工作',limits:'演示并不等同于独立实测'},en:{what:'A device running local models',change:'A dated new capability opened today',use:'Complete tasks through a real interaction',limits:'A demonstration is not an independent test'}},sources:[{label:'Official '+id,url:'https://example.com/'+id,publishedAt:'2026-10-06',isPrimary:true}],detailPages:[{id:'mechanism',zhTitle:'为什么这个机制重要',enTitle:'Why the mechanism matters',points:[{zh:'这条有来源的细节必须和图文一起保留',en:'This sourced detail must remain beside the figures and brief',sourceUrls:['https://example.com/'+id]}]}]});
const fixture=()=>({date:'2026-10-06',cutoff:'2026-10-06T12:42:00-04:00',timezone:'America/Toronto',zhTitle:'图文日报',enTitle:'Illustrated daily',zhSummary:'单页目录与单页参考，每个产品一页',enSummary:'One contents page, one references page, one page per product',topics:[topic('a'),topic('b')],contextTopics:[{...topic('old'),isNewToday:false,coverageKind:'first-inclusion-context',firstIncludedOn:'2026-10-06',event:{productKey:'old',kind:'patent-publication',occurredAt:'2026-10-01'}}]});
function run(root,data,extra=[]){writeFileSync(join(root,'issue.json'),JSON.stringify(data));return spawnSync('python3',[script,'--issue',join(root,'issue.json'),'--root',root,'--output-dir',join(root,'out'),...extra],{encoding:'utf8',timeout:120000});}
function pages(file){const r=spawnSync('python3',['-c','import json,sys;from pypdf import PdfReader;r=PdfReader(sys.argv[1]);print(json.dumps({"pages":[p.extract_text() for p in r.pages],"uris":[str(a.get_object().get("/A",{}).get("/URI","")) for p in r.pages for a in p.get("/Annots",[])]}))',file],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
test('Dense PDF has exactly one contents, one references and one complete page per fresh/context story',()=>{const root=mkdtempSync(join(tmpdir(),'daily-dense-'));try{const data=fixture(),r=run(root,data);assert.equal(r.status,0,r.stderr);for(const l of ['zh','en']){const p=pages(join(root,'out',`ai-daily-${data.date}-${l}.pdf`));assert.equal(p.pages.length,5);for(const [i,t] of [...data.topics,...data.contextTopics].entries()){const text=p.pages[i+1].replace(/\s/g,'');for(const s of [t[l+'Headline'],...Object.values(t.brief[l]),t.detailPages[0][l+'Title'],t.detailPages[0].points[0][l],t.event.occurredAt])assert.ok(text.includes(s.replace(/\s/g,'')),s);}assert.ok(p.pages[0].includes(l==='zh'?'目录':'Contents'));assert.ok(p.pages[4].includes(l==='zh'?'参考':'References'));assert.ok(p.uris.includes('https://example.com/a'));assert.ok(p.pages[3].includes(l==='zh'?'非今日新增':'Not new today'));}}finally{rmSync(root,{recursive:true,force:true});}});
test('Oversized story rejects with an editorial fit error instead of silent extra pages, clipping or shrinking',()=>{const root=mkdtempSync(join(tmpdir(),'daily-dense-overflow-'));try{const data=fixture();data.topics[0].detailPages[0].points[0].en='Long sourced detail '.repeat(2000);const r=run(root,data);assert.notEqual(r.status,0);assert.match(r.stderr,/editorial.*fit|fit.*editorial/i);assert.equal(existsSync(join(root,'out','ai-daily-2026-10-06-zh.pdf')),false);}finally{rmSync(root,{recursive:true,force:true});}});
test('Explicit shared page plan rejects missing or repeated stories and records exact editorial pagination',()=>{const root=mkdtempSync(join(tmpdir(),'daily-dense-plan-'));try{const data=fixture();const plan=[{id:'overview',type:'contents',topicIds:['a','b','old']},{id:'event-1',type:'product',topicIds:['a']},{id:'event-2',type:'product',topicIds:['b']},{id:'event-3',type:'context',topicIds:['old']},{id:'evidence-1',type:'references',topicIds:['a','b','old']}];writeFileSync(join(root,'plan.json'),JSON.stringify(plan));let r=run(root,data,['--page-plan',join(root,'plan.json')]);assert.equal(r.status,0,r.stderr);const metadata=JSON.parse(readFileSync(join(root,'out','pdf-export.json')));assert.deepEqual(metadata.editorialPagePlan,plan);writeFileSync(join(root,'plan.json'),JSON.stringify([...plan.slice(0,3),plan[1],plan[4]]));r=run(root,data,['--page-plan',join(root,'plan.json')]);assert.notEqual(r.status,0);assert.match(r.stderr,/page plan|story/i);}finally{rmSync(root,{recursive:true,force:true});}});
